<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    public function courses() {
        return $this->belongsToMany(Courses::class, 'user_course', 'user_id', 'course_id')
                    ->withPivot('status', 'booked_at')
                    ->withTimestamps();
    }

    // 2. Exams a student has taken and their marks (Many-to-Many)
    public function exams() {
        return $this->belongsToMany(Exam::class, 'exam_student', 'student_id', 'exam_id')
                    ->withPivot('mark')
                    ->withTimestamps();
    }

    // 3. Quizzes a student has taken and their points (Many-to-Many)
    public function quizzes() {
        return $this->belongsToMany(Quiz::class, 'quiz_student', 'student_id', 'quiz_id')
                    ->withPivot('points', 'comment')
                    ->withTimestamps();
    }

    /** * TEACHER RELATIONSHIPS 
     */

    // 4. Courses a teacher teaches (One-to-Many)
    public function teacherCourses() {
        return $this->hasMany(Courses::class, 'teacher_id');
    }

    // 5. Quizzes a teacher has announced (One-to-Many)
    public function announcedQuizzes() {
        return $this->hasMany(Quiz::class, 'teacher_id');
    }

    /** * PARENT RELATIONSHIPS 
     */

    // 6. Complaints sent to administration (One-to-Many)
    public function complaints() {
        return $this->hasMany(Complaint::class, 'parent_id');
    }

    // 7. Children linked to this parent (Many-to-Many via pivot table)
    public function children() {
        return $this->belongsToMany(User::class, 'parent_student', 'parent_id', 'student_id');
    }

    /** * ADMIN RELATIONSHIPS 
     */

    // 8. Polls created by an admin
    public function polls() {
        return $this->hasMany(Poll::class, 'admin_id');
    }

    // 9. Schedules generated by an admin
    public function schedules() {
        return $this->hasMany(Schedule::class, 'admin_id');
    }

    public function parents()
{
    // Assuming you used a pivot table named 'parent_student'
    return $this->belongsToMany(User::class, 'parent_student', 'student_id', 'parent_id');
}

    

    use HasApiTokens, HasFactory, Notifiable;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'phone_number',
        'health_state',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
